# Generated by Django 4.2 on 2023-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_all_stock_underlying_border_fetcheddata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_first_name', models.CharField(max_length=100)),
                ('Contact_last_name', models.CharField(max_length=100)),
                ('Contact_email', models.CharField(max_length=100)),
                ('Contact_phone_number', models.CharField(max_length=100)),
                ('Contact_messages', models.TextField(max_length=300)),
            ],
        ),
    ]
